#!/usr/bin/env python3
"""Generate FretBoardCrazies art assets via the OpenAI Images API.

Reads OPENAI_API_KEY from the environment. The anchor asset is generated from
the style spec; every other asset is generated by editing the anchor so the set
shares one visual identity. See scripts/README.md.
"""

import base64
import hashlib
import json
import os
import urllib.error
import urllib.request
import uuid
from dataclasses import dataclass

API_GENERATIONS_URL = "https://api.openai.com/v1/images/generations"
API_EDITS_URL = "https://api.openai.com/v1/images/edits"
MODEL = "gpt-image-1"
OUTPUT_DIR = "art"
CANDIDATES_DIR = os.path.join(OUTPUT_DIR, "_candidates")
ANCHOR_PATH = os.path.join(OUTPUT_DIR, "_anchor.png")
GALLERY_PATH = os.path.join(OUTPUT_DIR, "index.html")

STYLE_SPEC = {
    "shape_language": "chunky rounded shapes",
    "line_weight": "thick clean outlines",
    "lighting": "soft drop shadow and gentle gradients",
    "palette": (
        "warm orange #FF8A3D and amber #FFB23E primaries, teal #2DD4BF accents, "
        "soft cream #FFF6EC background"
    ),
}


def build_style_prefix(spec):
    return (
        f"flat vector illustration, playful and friendly, {spec['shape_language']}, "
        f"{spec['line_weight']}, {spec['lighting']}, warm palette ({spec['palette']}), "
        "Duolingo-style illustration, high detail, centered. "
    )


STYLE_PREFIX = build_style_prefix(STYLE_SPEC)

BELT_COLORS = ["white", "yellow", "orange", "green", "blue", "purple", "brown", "black"]


@dataclass(frozen=True)
class Asset:
    name: str
    group: str
    prompt_body: str
    size: str
    transparent: bool
    anchored: bool


ASSETS = [
    Asset(
        "_anchor",
        "anchor",
        "a style reference tile arranging a guitar pick, a five-point star, and a "
        "rounded badge together to showcase the palette, line weight, and shading",
        "1024x1024",
        False,
        False,
    ),
    Asset(
        "app-icon",
        "icon",
        "app icon: a cheerful stylized guitar fretboard with one glowing note dot, "
        "rounded-square composition, warm orange-to-amber background, iconic and "
        "simple, readable when small",
        "1024x1024",
        False,
        True,
    ),
    *[
        Asset(
            f"belt-{color}",
            "belts",
            f"a cute knotted martial-arts belt icon in {color}, tied in a bow with "
            "two hanging ends, glossy, rounded, badge style, with a thin light "
            "outline so it reads on dark backgrounds",
            "1024x1024",
            True,
            True,
        )
        for color in BELT_COLORS
    ],
    Asset(
        "flame-small",
        "combo",
        "a small friendly cartoon flame spark, orange-yellow gradient, expressive",
        "1024x1024",
        True,
        True,
    ),
    Asset(
        "flame-large",
        "combo",
        "a big roaring friendly cartoon flame, orange-yellow gradient, energetic "
        "and expressive",
        "1024x1024",
        True,
        True,
    ),
    Asset(
        "combo-burst",
        "combo",
        "a celebratory burst graphic with stars and sparks conveying combo energy, "
        "warm colors",
        "1024x1024",
        True,
        True,
    ),
    Asset(
        "correct-sticker",
        "success",
        "a happy confetti starburst sticker conveying a 'Nice!' celebration moment, "
        "rounded and bright",
        "1024x1024",
        True,
        True,
    ),
]

COST_TABLE = {
    ("1024x1024", "low"): 0.011,
    ("1024x1024", "medium"): 0.042,
    ("1024x1024", "high"): 0.167,
}


def resolve_selection(tokens, assets):
    if not tokens:
        return list(assets)
    by_name = {asset.name: asset for asset in assets}
    group_names = {asset.group for asset in assets}
    selected = []
    unknown = []
    for token in tokens:
        if token in by_name:
            selected.append(by_name[token])
        elif token in group_names:
            selected.extend(asset for asset in assets if asset.group == token)
        else:
            unknown.append(token)
    if unknown:
        raise ValueError(f"Unknown group(s)/asset(s): {', '.join(unknown)}")
    seen = set()
    deduped = []
    for asset in selected:
        if asset.name not in seen:
            seen.add(asset.name)
            deduped.append(asset)
    return deduped


def estimate_cost(assets, quality, variants, cost_table):
    return sum(cost_table[(asset.size, quality)] * variants for asset in assets)


def build_prompt(asset, style_prefix):
    return style_prefix + asset.prompt_body


def build_generation_payload(asset, prompt, quality):
    return {
        "model": MODEL,
        "prompt": prompt,
        "size": asset.size,
        "n": 1,
        "quality": quality,
        "background": "transparent" if asset.transparent else "opaque",
    }


def build_edit_fields(asset, prompt, quality):
    return {
        "model": MODEL,
        "prompt": prompt,
        "size": asset.size,
        "n": "1",
        "quality": quality,
        "background": "transparent" if asset.transparent else "opaque",
    }


def build_sidecar(asset, prompt, quality, anchor_digest, model, timestamp):
    return {
        "name": asset.name,
        "group": asset.group,
        "prompt": prompt,
        "size": asset.size,
        "quality": quality,
        "transparent": asset.transparent,
        "anchored": asset.anchored,
        "anchor_hash": anchor_digest,
        "model": model,
        "timestamp": timestamp,
    }


def anchor_hash(path):
    if not os.path.exists(path):
        return None
    with open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def should_skip(path, force):
    return os.path.exists(path) and not force


def encode_multipart(fields, files):
    boundary = uuid.uuid4().hex
    parts = []
    for name, value in fields.items():
        parts.append(
            (
                f'--{boundary}\r\nContent-Disposition: form-data; name="{name}"\r\n\r\n'
                f"{value}\r\n"
            ).encode("utf-8")
        )
    for name, (filename, content, content_type) in files.items():
        header = (
            f'--{boundary}\r\nContent-Disposition: form-data; name="{name}"; '
            f'filename="{filename}"\r\nContent-Type: {content_type}\r\n\r\n'
        ).encode("utf-8")
        parts.append(header + content + b"\r\n")
    parts.append(f"--{boundary}--\r\n".encode("utf-8"))
    return boundary, b"".join(parts)


def post_generation(url, payload, api_key):
    request = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=180) as response:
        body = json.loads(response.read().decode("utf-8"))
    return base64.b64decode(body["data"][0]["b64_json"])


def post_edit(url, fields, image_path, api_key):
    with open(image_path, "rb") as handle:
        image_bytes = handle.read()
    boundary, body = encode_multipart(
        fields, {"image": (os.path.basename(image_path), image_bytes, "image/png")}
    )
    request = urllib.request.Request(
        url,
        data=body,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": f"multipart/form-data; boundary={boundary}",
        },
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=180) as response:
        result = json.loads(response.read().decode("utf-8"))
    return base64.b64decode(result["data"][0]["b64_json"])


def generate_one(asset, prompt, quality, api_key, anchor_path):
    if asset.anchored and os.path.exists(anchor_path):
        return post_edit(
            API_EDITS_URL,
            build_edit_fields(asset, prompt, quality),
            anchor_path,
            api_key,
        )
    return post_generation(
        API_GENERATIONS_URL, build_generation_payload(asset, prompt, quality), api_key
    )
