#!/usr/bin/env python3
"""Generate FretBoardCrazies art assets via the OpenAI Images API.

Reads OPENAI_API_KEY from the environment. The anchor asset is generated from
the style spec; every other asset is generated by editing the anchor so the set
shares one visual identity. See scripts/README.md.
"""

import argparse
import base64
import hashlib
import html
import json
import os
import shutil
import subprocess
import sys
import urllib.error
import urllib.request
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone

API_GENERATIONS_URL = "https://api.openai.com/v1/images/generations"
API_EDITS_URL = "https://api.openai.com/v1/images/edits"
MODEL = "gpt-image-1"
OUTPUT_DIR = "art"
CANDIDATES_DIR = os.path.join(OUTPUT_DIR, "_candidates")
ANCHOR_PATH = os.path.join(OUTPUT_DIR, "_anchor.png")
GALLERY_PATH = os.path.join(OUTPUT_DIR, "index.html")

STYLE_SPEC = {
    "shape_language": "chunky rounded shapes",
    "line_weight": "thick clean outlines",
    "lighting": "soft drop shadow and gentle gradients",
    "palette": (
        "warm orange #FF8A3D and amber #FFB23E primaries, teal #2DD4BF accents, "
        "soft cream #FFF6EC background"
    ),
}


def build_style_prefix(spec):
    return (
        f"flat vector illustration, playful and friendly, {spec['shape_language']}, "
        f"{spec['line_weight']}, {spec['lighting']}, warm palette ({spec['palette']}), "
        "Duolingo-style illustration, high detail, centered. "
    )


STYLE_PREFIX = build_style_prefix(STYLE_SPEC)

BELT_COLORS = ["white", "yellow", "orange", "green", "blue", "purple", "brown", "black"]


@dataclass(frozen=True)
class Asset:
    name: str
    group: str
    prompt_body: str
    size: str
    transparent: bool
    anchored: bool


ASSETS = [
    Asset(
        "_anchor",
        "anchor",
        "a style reference tile arranging a guitar pick, a five-point star, and a "
        "rounded badge together to showcase the palette, line weight, and shading",
        "1024x1024",
        False,
        False,
    ),
    Asset(
        "app-icon",
        "icon",
        "app icon: a cheerful stylized guitar fretboard with one glowing note dot, "
        "rounded-square composition, warm orange-to-amber background, iconic and "
        "simple, readable when small",
        "1024x1024",
        False,
        True,
    ),
    *[
        Asset(
            f"belt-{color}",
            "belts",
            f"a cute knotted martial-arts belt icon in {color}, tied in a bow with "
            "two hanging ends, glossy, rounded, badge style, with a thin light "
            "outline so it reads on dark backgrounds",
            "1024x1024",
            True,
            True,
        )
        for color in BELT_COLORS
    ],
    Asset(
        "flame-small",
        "combo",
        "a small friendly cartoon flame spark, orange-yellow gradient, expressive",
        "1024x1024",
        True,
        True,
    ),
    Asset(
        "flame-large",
        "combo",
        "a big roaring friendly cartoon flame, orange-yellow gradient, energetic "
        "and expressive",
        "1024x1024",
        True,
        True,
    ),
    Asset(
        "combo-burst",
        "combo",
        "a celebratory burst graphic with stars and sparks conveying combo energy, "
        "warm colors",
        "1024x1024",
        True,
        True,
    ),
    Asset(
        "correct-sticker",
        "success",
        "a happy confetti starburst sticker conveying a 'Nice!' celebration moment, "
        "rounded and bright",
        "1024x1024",
        True,
        True,
    ),
]

COST_TABLE = {
    ("1024x1024", "low"): 0.011,
    ("1024x1024", "medium"): 0.042,
    ("1024x1024", "high"): 0.167,
}


def resolve_selection(tokens, assets):
    if not tokens:
        return list(assets)
    by_name = {asset.name: asset for asset in assets}
    group_names = {asset.group for asset in assets}
    selected = []
    unknown = []
    for token in tokens:
        if token in by_name:
            selected.append(by_name[token])
        elif token in group_names:
            selected.extend(asset for asset in assets if asset.group == token)
        else:
            unknown.append(token)
    if unknown:
        raise ValueError(f"Unknown group(s)/asset(s): {', '.join(unknown)}")
    seen = set()
    deduped = []
    for asset in selected:
        if asset.name not in seen:
            seen.add(asset.name)
            deduped.append(asset)
    return deduped


def estimate_cost(assets, quality, variants, cost_table):
    return sum(cost_table[(asset.size, quality)] * variants for asset in assets)


def build_prompt(asset, style_prefix):
    return style_prefix + asset.prompt_body


def build_generation_payload(asset, prompt, quality):
    return {
        "model": MODEL,
        "prompt": prompt,
        "size": asset.size,
        "n": 1,
        "quality": quality,
        "background": "transparent" if asset.transparent else "opaque",
    }


def build_edit_fields(asset, prompt, quality):
    return {
        "model": MODEL,
        "prompt": prompt,
        "size": asset.size,
        "n": "1",
        "quality": quality,
        "background": "transparent" if asset.transparent else "opaque",
    }


def build_sidecar(asset, prompt, quality, anchor_digest, model, timestamp):
    return {
        "name": asset.name,
        "group": asset.group,
        "prompt": prompt,
        "size": asset.size,
        "quality": quality,
        "transparent": asset.transparent,
        "anchored": asset.anchored,
        "anchor_hash": anchor_digest,
        "model": model,
        "timestamp": timestamp,
    }


def anchor_hash(path):
    if not os.path.exists(path):
        return None
    with open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def should_skip(path, force):
    return os.path.exists(path) and not force


def encode_multipart(fields, files):
    boundary = uuid.uuid4().hex
    parts = []
    for name, value in fields.items():
        parts.append(
            (
                f'--{boundary}\r\nContent-Disposition: form-data; name="{name}"\r\n\r\n'
                f"{value}\r\n"
            ).encode("utf-8")
        )
    for name, (filename, content, content_type) in files.items():
        header = (
            f'--{boundary}\r\nContent-Disposition: form-data; name="{name}"; '
            f'filename="{filename}"\r\nContent-Type: {content_type}\r\n\r\n'
        ).encode("utf-8")
        parts.append(header + content + b"\r\n")
    parts.append(f"--{boundary}--\r\n".encode("utf-8"))
    return boundary, b"".join(parts)


def post_generation(url, payload, api_key):
    request = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=180) as response:
        body = json.loads(response.read().decode("utf-8"))
    return base64.b64decode(body["data"][0]["b64_json"])


def post_edit(url, fields, image_path, api_key):
    with open(image_path, "rb") as handle:
        image_bytes = handle.read()
    boundary, body = encode_multipart(
        fields, {"image": (os.path.basename(image_path), image_bytes, "image/png")}
    )
    request = urllib.request.Request(
        url,
        data=body,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": f"multipart/form-data; boundary={boundary}",
        },
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=180) as response:
        result = json.loads(response.read().decode("utf-8"))
    return base64.b64decode(result["data"][0]["b64_json"])


def generate_one(asset, prompt, quality, api_key, anchor_path):
    if asset.anchored and os.path.exists(anchor_path):
        return post_edit(
            API_EDITS_URL,
            build_edit_fields(asset, prompt, quality),
            anchor_path,
            api_key,
        )
    return post_generation(
        API_GENERATIONS_URL, build_generation_payload(asset, prompt, quality), api_key
    )


def render_gallery(entries):
    figures = []
    for entry in entries:
        figures.append(
            f'<figure><img src="{html.escape(entry["image"], quote=True)}" width="256" loading="lazy">'
            f"<figcaption><b>{html.escape(entry['name'])}</b> ({html.escape(entry['quality'])})<br>"
            f"{html.escape(entry['prompt'])}</figcaption></figure>"
        )
    return (
        "<!doctype html><meta charset=utf-8><title>FretBoardCrazies art</title>"
        "<style>body{font-family:-apple-system,sans-serif;background:#FFF6EC;padding:24px}"
        "figure{display:inline-block;width:288px;vertical-align:top;margin:0 16px 24px 0}"
        "img{background:#e9ddcc;border-radius:12px}"
        "figcaption{font-size:12px;color:#221A14}</style>"
        "<body>" + "".join(figures) + "</body>"
    )


def promote(name, index, candidates_dir, output_dir):
    source_png = os.path.join(candidates_dir, f"{name}-{index}.png")
    if not os.path.exists(source_png):
        raise FileNotFoundError(source_png)
    destination_png = os.path.join(output_dir, f"{name}.png")
    shutil.copyfile(source_png, destination_png)
    source_json = os.path.join(candidates_dir, f"{name}-{index}.json")
    if os.path.exists(source_json):
        shutil.copyfile(source_json, os.path.join(output_dir, f"{name}.json"))
    return destination_png


def parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Generate FretBoardCrazies art assets."
    )
    parser.add_argument(
        "selection", nargs="*", help="group or asset names; empty means all"
    )
    parser.add_argument(
        "--list", action="store_true", help="list groups/assets and exit"
    )
    parser.add_argument(
        "--variants", type=int, default=1, help="write N candidates instead of a final"
    )
    parser.add_argument("--promote", help="promote a candidate, format name=index")
    parser.add_argument("--final", action="store_true", help="generate at high quality")
    parser.add_argument(
        "--force", action="store_true", help="overwrite existing finals"
    )
    parser.add_argument(
        "--yes", action="store_true", help="skip the spend confirmation"
    )
    return parser.parse_args(argv)


def _write_image_and_sidecar(
    directory, filename, image_bytes, asset, prompt, quality, digest, timestamp
):
    os.makedirs(directory, exist_ok=True)
    image_path = os.path.join(directory, f"{filename}.png")
    with open(image_path, "wb") as handle:
        handle.write(image_bytes)
    sidecar = build_sidecar(asset, prompt, quality, digest, MODEL, timestamp)
    with open(os.path.join(directory, f"{filename}.json"), "w") as handle:
        json.dump(sidecar, handle, indent=2)
    return image_path


def _gallery_entries(directory, quality, src_prefix=""):
    entries = []
    for filename in sorted(os.listdir(directory)):
        if not filename.endswith(".png"):
            continue
        name = filename[:-4]
        sidecar_path = os.path.join(directory, f"{name}.json")
        prompt = ""
        entry_quality = quality
        if os.path.exists(sidecar_path):
            with open(sidecar_path) as handle:
                data = json.load(handle)
            prompt = data.get("prompt", "")
            entry_quality = data.get("quality", quality)
        entries.append(
            {
                "name": name,
                "image": src_prefix + filename,
                "prompt": prompt,
                "quality": entry_quality,
            }
        )
    return entries


def run(args, assets, api_key, timestamp):
    if args.promote:
        name, _, index = args.promote.partition("=")
        promote(name, int(index), CANDIDATES_DIR, OUTPUT_DIR)
        print(f"Promoted {name}-{index} to {OUTPUT_DIR}/{name}.png")
        return 0

    selected = resolve_selection(args.selection, assets)
    quality = "high" if args.final else "low"

    if args.list:
        for asset in selected:
            print(f"{asset.group}/{asset.name}")
        return 0

    estimate = estimate_cost(selected, quality, args.variants, COST_TABLE)
    print(
        f"About to generate {len(selected) * args.variants} image(s) at {quality} "
        f"quality (~${estimate:.2f})."
    )
    if not args.yes:
        if input("Proceed? [y/N] ").strip().lower() != "y":
            print("Aborted.")
            return 1

    spent = 0.0
    for asset in selected:
        digest = anchor_hash(ANCHOR_PATH)
        prompt = build_prompt(asset, STYLE_PREFIX)
        final_path = os.path.join(OUTPUT_DIR, f"{asset.name}.png")
        if args.variants == 1 and should_skip(final_path, args.force):
            print(f"  skip {asset.name} (exists; use --force)")
            continue
        if args.variants > 1:
            for index in range(1, args.variants + 1):
                image_bytes = generate_one(asset, prompt, quality, api_key, ANCHOR_PATH)
                _write_image_and_sidecar(
                    CANDIDATES_DIR,
                    f"{asset.name}-{index}",
                    image_bytes,
                    asset,
                    prompt,
                    quality,
                    digest,
                    timestamp,
                )
                spent += COST_TABLE[(asset.size, quality)]
                print(f"  candidate {asset.name}-{index}  (~${spent:.2f})")
        else:
            image_bytes = generate_one(asset, prompt, quality, api_key, ANCHOR_PATH)
            _write_image_and_sidecar(
                OUTPUT_DIR,
                asset.name,
                image_bytes,
                asset,
                prompt,
                quality,
                digest,
                timestamp,
            )
            spent += COST_TABLE[(asset.size, quality)]
            print(f"  {asset.name}  (~${spent:.2f})")

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    if args.variants > 1:
        entries = _gallery_entries(CANDIDATES_DIR, quality, "_candidates/")
    else:
        entries = _gallery_entries(OUTPUT_DIR, quality)
    with open(GALLERY_PATH, "w") as handle:
        handle.write(render_gallery(entries))
    print(f"Gallery written to {GALLERY_PATH}")
    return 0


def main():
    args = parse_args(sys.argv[1:])
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key and not args.list and not args.promote:
        print(
            "OPENAI_API_KEY is not set. Copy .env.example to .env, fill it, and "
            "load it (see scripts/README.md)."
        )
        sys.exit(1)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    try:
        code = run(args, ASSETS, api_key, timestamp)
    except (ValueError, FileNotFoundError) as error:
        print(f"Error: {error}")
        sys.exit(1)
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", "replace")
        print(f"OpenAI API error: HTTP {error.code} {detail[:300]}")
        sys.exit(1)
    if code == 0 and not args.list and not args.promote:
        subprocess.run(["open", GALLERY_PATH], check=False)
    sys.exit(code)


if __name__ == "__main__":
    main()
